# Generated by Django 3.0.3 on 2020-02-23 16:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.avatar_path, validators=[core.utils.validate_file_size]),
        ),
    ]
