# Generated by Django 3.0.3 on 2020-02-23 16:31

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import optimized_image.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1024)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('geopoint', models.CharField(max_length=100)),
                ('pickup_times', multiselectfield.db.fields.MultiSelectField(choices=[('monday_morning', 'Lunes Mañana (6AM a 12M)'), ('monday_afternoon', 'Lunes Tarde (12M a 6PM)'), ('monday_night', 'Lunes Noche (6PM a 1AM)'), ('tuesday_morning', 'Martes Mañana (6AM a 12M)'), ('tuesday_afternoon', 'Martes Tarde (12M a 6PM)'), ('tuesday_night', 'Martes Noche (6PM a 1AM)'), ('wednesday_morning', 'Miercoles Mañana (6AM a 12M)'), ('wednesday_afternoon', 'Miercoles Tarde (12M a 6PM)'), ('wednesday_night', 'Miercoles Noche (6PM a 1AM)'), ('thursday_morning', 'Jueves Mañana (6AM a 12M)'), ('thursday_afternoon', 'Jueves Tarde (12M a 6PM)'), ('thursday_night', 'Jueves Noche (6PM a 1AM)'), ('friday_morning', 'Viernes Mañana (6AM a 12M)'), ('friday_afternoon', 'Viernes Tarde (12M a 6PM)'), ('friday_night', 'Viernes Noche (6PM a 1AM)'), ('saturday_morning', 'Sábado Mañana (6AM a 12M)'), ('saturday_afternoon', 'Sábado Tarde (12M a 6PM)'), ('saturday_night', 'Sábado Noche (6PM a 1AM)'), ('sunday_morning', 'Domingo Mañana (6AM a 12M)'), ('sunday_afternoon', 'Domingo Tarde (12M a 6PM)'), ('sunday_night', 'Domingo Noche (6PM a 1AM)')], max_length=338)),
                ('waste_disposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_disposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPhotos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('primary_photo', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=core.utils.image_path)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hoarding.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', optimized_image.fields.OptimizedImageField(blank=True, upload_to=core.utils.image_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoarding.ItemPhotos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
