# Generated by Django 3.0.3 on 2020-02-22 21:51

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import optimized_image.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hoarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionschedule',
            name='friday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='monday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='saturday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='sunday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='thursday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='tuesday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='wednesday',
            field=models.CharField(choices=[('morning', 'Mañana (6AM a 12M)'), ('afternoon', 'Tarde (12M a 6PM)'), ('night', 'Noche (6PM a 1AM)'), ('unavailable', 'No disponible')], max_length=32),
        ),
        migrations.CreateModel(
            name='ItemPhotos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('primary_photo', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=core.utils.image_path)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hoarding.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', optimized_image.fields.OptimizedImageField(blank=True, upload_to=core.utils.image_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoarding.ItemPhotos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
