# Generated by Django 3.0.3 on 2020-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarding', '0002_auto_20200222_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
