# Generated by Django 3.0.3 on 2020-02-22 23:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hoarding', '0003_item_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection_schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday_morning', 'Lunes Mañana (6AM a 12M)'), ('monday_afternoon', 'Lunes Tarde (12M a 6PM)'), ('monday_night', 'Lunes Noche (6PM a 1AM)'), ('tuesday_morning', 'Martes Mañana (6AM a 12M)'), ('tuesday_afternoon', 'Martes Tarde (12M a 6PM)'), ('tuesday_night', 'Martes Noche (6PM a 1AM)'), ('wednesday_morning', 'Miercoles Mañana (6AM a 12M)'), ('wednesday_afternoon', 'Miercoles Tarde (12M a 6PM)'), ('wednesday_night', 'Miercoles Noche (6PM a 1AM)'), ('thursday_morning', 'Jueves Mañana (6AM a 12M)'), ('thursday_afternoon', 'Jueves Tarde (12M a 6PM)'), ('thursday_night', 'Jueves Noche (6PM a 1AM)'), ('friday_morning', 'Viernes Mañana (6AM a 12M)'), ('friday_afternoon', 'Viernes Tarde (12M a 6PM)'), ('friday_night', 'Viernes Noche (6PM a 1AM)'), ('saturday_morning', 'Sábado Mañana (6AM a 12M)'), ('saturday_afternoon', 'Sábado Tarde (12M a 6PM)'), ('saturday_night', 'Sábado Noche (6PM a 1AM)'), ('sunday_morning', 'Domingo Mañana (6AM a 12M)'), ('sunday_afternoon', 'Domingo Tarde (12M a 6PM)'), ('sunday_night', 'Domingo Noche (6PM a 1AM)')], max_length=338),
        ),
        migrations.DeleteModel(
            name='CollectionSchedule',
        ),
    ]
