# Generated by Django 3.0.3 on 2020-02-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoarding', '0004_auto_20200222_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='collection_schedule',
            new_name='pickup_times',
        ),
    ]
